In [2]:
import pandas as pd

In [3]:
pwd

'/home/play/workspace'

In [4]:
df = pd.read_csv("./data/speeddating.csv")

In [5]:
df.loc[:, (df.dtypes == 'object').values] = df.loc[:, (df.dtypes == 'object').values].map(lambda x: x.replace("b'", '').\
                                              replace("'", ""))

In [6]:
df.columns

Index(['has_null', 'wave', 'gender', 'age', 'age_o', 'd_age', 'd_d_age',
       'race', 'race_o', 'samerace',
       ...
       'd_expected_num_interested_in_me', 'd_expected_num_matches', 'like',
       'guess_prob_liked', 'd_like', 'd_guess_prob_liked', 'met', 'decision',
       'decision_o', 'match'],
      dtype='object', length=123)

In [7]:
df.columns.size

123

In [8]:
df['match'].value_counts()

match
0    6998
1    1380
Name: count, dtype: int64

In [9]:
df

,has_null,wave,gender,age,age_o,d_age,d_d_age,race,race_o,samerace,...,d_expected_num_interested_in_me,d_expected_num_matches,like,guess_prob_liked,d_like,d_guess_prob_liked,met,decision,decision_o,match
0,,1.0,female,21.0,27.0,6.0,[4-6],Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,...,[0-3],[3-5],7.0,6.0,[6-8],[5-6],0.0,1,0,0
1,,1.0,female,21.0,22.0,1.0,[0-1],Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,...,[0-3],[3-5],7.0,5.0,[6-8],[5-6],1.0,1,0,0
2,,1.0,female,21.0,22.0,1.0,[0-1],Asian/Pacific Islander/Asian-American,Asian/Pacific Islander/Asian-American,1,...,[0-3],[3-5],7.0,NaN,[6-8],[0-4],1.0,1,1,1
3,,1.0,female,21.0,23.0,2.0,[2-3],Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,...,[0-3],[3-5],7.0,6.0,[6-8],[5-6],0.0,1,1,1
4,,1.0,female,21.0,24.0,3.0,[2-3],Asian/Pacific Islander/Asian-American,Latino/Hispanic American,0,...,[0-3],[3-5],6.0,6.0,[6-8],[5-6],0.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,,21.0,male,25.0,26.0,1.0,[0-1],European/Caucasian-American,Latino/Hispanic American,0,...,[0-3],[3-5],2.0,5.0,[0-5],[5-6],0.0,0,1,0
8374,,21.0,male,25.0,24.0,1.0,[0-1],European/Caucasian-American,Other,0,...,[0-3],[3-5],4.0,4.0,[0-5],[0-4],0.0,0,0,0
8375,,21.0,male,25.0,29.0,4.0,[4-6],European/Caucasian-American,Latino/Hispanic American,0,...,[0-3],[3-5],6.0,5.0,[6-8],[5-6],0.0,0,0,0
8376,,21.0,male,25.0,22.0,3.0,[2-3],European/Caucasian-American,Asian/Pacific Islander/Asian-American,0,...,[0-3],[3-5],5.0,5.0,[0-5],[5-6],0.0,0,1,0
8377,,21.0,male,25.0,22.0,3.0,[2-3],European/Caucasian-American,Asian/Pacific Islander/Asian-American,0,...,[0-3],[3-5],4.0,5.0,[0-5],[5-6],0.0,0,1,0