In [45]:
a = 1

In [46]:
a

1

In [47]:
True

True

In [48]:
False

False

In [49]:
1a = 10

SyntaxError: invalid decimal literal (482919702.py, line 1)

In [50]:
apple%fs = 10

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (4272829560.py, line 1)

In [51]:
text = "동해물과 백두산이"

In [52]:
print(text)

동해물과 백두산이

In [53]:
text[0]

'동'

In [54]:
text[3]

'과'

In [55]:
#text[start:end+1]

In [58]:
text[2:8]

'물과 백두산'

In [59]:
text[3:]

'동해물과 백'

In [60]:
text[3:]

'과 백두산이'

In [61]:
#text[start:end+1:step]

In [62]:
text[0:8:2]

'동물 두'

In [63]:
text[::2]

'동물 두이'

In [64]:
text2 = "sdfasdfafhsdhafijiiasflk"

In [66]:
text2[-3:]

'flk'

In [67]:
text[::-1]

'이산두백 과물해동'

In [68]:
import requests

In [71]:
head = {
    'User-Agent':
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0'
}

In [75]:
r = requests.get("https://m.stock.naver.com/front-api/external/chart/domestic/info?symbol=005930&requestType=1&startTime=20210213&endTime=20211029&timeframe=day"
                ,headers=head)

In [79]:
data = eval(r.text.strip())

In [82]:
data[::-1]

[['20211029', 71200, 71600, 69700, 69800, 17016151, 51.26],
 ['20211028', 69500, 72200, 69500, 70700, 20644902, 51.3],
 ['20211027', 71000, 71000, 70000, 70100, 10295316, 51.34],
 ['20211026', 70600, 71500, 70400, 71100, 10528252, 51.38],
 ['20211025', 69900, 70600, 69500, 70200, 10029621, 51.39],
 ['20211022', 70000, 70700, 70000, 70400, 8395448, 51.42],
 ['20211021', 70300, 70600, 70000, 70200, 10891094, 51.43],
 ['20211020', 70700, 71000, 70200, 70300, 10151638, 51.44],
 ['20211019', 70800, 71000, 70400, 70600, 9507991, 51.43],
 ['20211018', 70200, 70300, 69200, 70200, 13486391, 51.44],
 ['20211015', 70200, 71000, 70000, 70100, 18051612, 51.42],
 ['20211014', 69000, 69800, 68800, 69400, 19520641, 51.45],
 ['20211013', 68700, 69600, 68300, 68800, 24172015, 51.51],
 ['20211012', 70700, 70900, 68700, 69000, 31001484, 51.6],
 ['20211008', 72300, 72400, 71500, 71500, 14043287, 51.76],
 ['20211007', 71600, 72100, 71300, 71600, 13683532, 51.76],
 ['20211006', 72600, 72800, 71200, 71300, 18956962, 51.8],
 ['20211005', 73000, 73000, 71400, 72200, 24013921, 51.81],
 ['20211001', 73900, 74000, 72900, 73200, 15803395, 51.84],
 ['20210930', 74300, 74800, 73700, 74100, 19919361, 51.86],
 ['20210929', 74800, 75300, 73800, 74100, 23992458, 51.86],
 ['20210928', 77700, 77800, 76200, 76300, 15406382, 51.99],
 ['20210927', 77300, 77700, 77000, 77700, 11699798, 52.0],
 ['20210924', 77600, 77700, 77100, 77300, 12247274, 51.98],
 ['20210923', 77500, 77600, 76800, 77400, 17055590, 51.98],
 ['20210917', 76300, 77200, 75900, 77200, 16289502, 51.93],
 ['20210916', 77300, 77400, 76100, 76100, 13067622, 51.88],
 ['20210915', 77400, 77400, 76400, 77000, 12829128, 51.88],
 ['20210914', 77100, 77700, 76600, 76600, 18167057, 51.85],
 ['20210913', 75200, 76300, 75100, 76300, 11397775, 51.8],
 ['20210910', 75300, 75600, 74800, 75300, 10103212, 51.77],
 ['20210909', 76400, 76600, 75000, 75300, 17600770, 51.81],
 ['20210908', 76000, 76400, 75600, 76300, 11798147, 51.8],
 ['20210907', 77100, 77100, 75900, 76100, 13239401, 51.79],
 ['20210906', 76800, 77600, 76600, 77300, 12861180, 51.83],
 ['20210903', 76400, 76700, 76000, 76600, 12096419, 51.8],
 ['20210902', 76800, 76800, 75700, 76000, 15347486, 51.76],
 ['20210901', 76700, 77100, 75900, 76800, 16114775, 51.76],
 ['20210831', 74900, 76700, 74300, 76700, 24630370, 51.7],
 ['20210830', 75400, 75500, 74200, 74600, 12686999, 51.61],
 ['20210827', 74300, 75000, 73800, 74300, 15172748, 51.64],
 ['20210826', 76100, 76200, 74600, 74600, 16671494, 51.68],
 ['20210825', 76200, 76600, 74900, 75700, 22319664, 51.71],
 ['20210824', 73900, 75700, 73900, 75600, 21016913, 51.7],
 ['20210823', 73300, 74000, 73000, 73300, 19384648, 51.7],
 ['20210820', 73500, 73900, 72500, 72700, 22364803, 51.76],
 ['20210819', 73500, 74400, 73100, 73100, 22166298, 51.82],
 ['20210818', 73900, 74600, 73100, 73900, 29192631, 51.86],
 ['20210817', 74000, 75100, 74000, 74200, 30944847, 52.02],
 ['20210813', 75800, 76000, 74100, 74400, 61270643, 52.12],
 ['20210812', 77100, 78200, 76900, 77000, 42365223, 52.65],
 ['20210811', 79600, 79800, 78500, 78500, 30241137, 53.02],
 ['20210810', 82300, 82400, 80100, 80200, 20362639, 53.25],
 ['20210809', 81500, 82300, 80900, 81500, 15522581, 53.34],
 ['20210806', 81900, 82500, 81300, 81500, 13342623, 53.35],
 ['20210805', 83300, 83300, 82000, 82100, 18485469, 53.35],
 ['20210804', 82200, 83100, 81800, 82900, 25642368, 53.38],
 ['20210803', 79400, 81400, 79300, 81400, 24339360, 53.27],
 ['20210802', 79200, 79500, 78700, 79300, 11739124, 53.15],
 ['20210730', 78900, 78900, 78500, 78500, 13823411, 53.17],
 ['20210729', 78800, 79400, 78800, 79000, 14360453, 53.19],
 ['20210728', 78300, 79200, 78100, 79200, 12743417, 53.22],
 ['20210727', 79200, 79400, 78500, 78500, 11427693, 53.27],
 ['20210726', 79400, 79500, 78800, 78800, 10040975, 53.3],
 ['20210723', 79700, 79900, 79200, 79300, 9098910, 53.33],
 ['20210722', 79000, 79800, 78900, 79700, 12618790, 53.35],
 ['20210721', 79000, 79100, 78500, 78500, 12355296, 53.35],
 ['20210720', 78500, 79000, 78400, 79000, 12456646, 53.4],
 ['20210719', 79100, 79200, 78800, 79000, 13155414, 53.43],
 ['20210716', 80100, 80100, 79500, 79800, 10859399, 53.49],
 ['20210715', 79800, 80600, 79500, 80600, 13766279, 53.49],
 ['20210714', 79400, 79600, 79100, 79500, 11575636, 53.45],
 ['20210713', 80000, 80200, 79800, 79800, 9863450, 53.46],
 ['20210712', 79900, 80000, 79500, 79700, 9768108, 53.46],
 ['20210709', 79600, 79800, 79000, 79400, 22720577, 53.47],
 ['20210708', 81100, 81200, 79900, 79900, 16660998, 53.57],
 ['20210707', 81200, 81300, 80300, 80800, 15992202, 53.59],
 ['20210706', 80600, 81200, 80500, 81200, 12131651, 53.59],
 ['20210705', 80100, 80800, 80000, 80400, 8330969, 53.54],
 ['20210702', 80000, 80400, 79900, 80000, 8753097, 53.5],
 ['20210701', 80500, 80600, 80000, 80100, 13382882, 53.54],
 ['20210630', 81100, 81400, 80700, 80700, 13288643, 53.57],
 ['20210629', 81900, 82100, 80800, 81000, 15744317, 53.55],
 ['20210628', 81700, 82000, 81600, 81900, 11578529, 53.53],
 ['20210625', 81500, 81900, 81200, 81600, 13481405, 53.57],
 ['20210624', 80400, 81400, 80100, 81200, 18771080, 53.61],
 ['20210623', 80500, 80600, 79900, 80100, 13856548, 53.6],
 ['20210622', 80200, 80300, 79900, 80000, 11773365, 53.62],
 ['20210621', 79700, 80000, 79600, 79900, 16063340, 53.66],
 ['20210618', 81100, 81100, 80500, 80500, 14916721, 53.73],
 ['20210617', 81100, 81300, 80700, 80900, 14007385, 53.82],
 ['20210616', 81500, 81900, 81100, 81800, 14999855, 53.84],
 ['20210615', 80900, 81200, 80600, 80900, 10075685, 53.79],
 ['20210614', 80800, 80900, 80500, 80500, 10550078, 53.79],
 ['20210611', 81200, 81700, 80700, 81000, 14087962, 53.81],
 ['20210610', 81300, 81400, 80900, 81000, 17586995, 53.86],
 ['20210609', 81500, 82000, 81100, 81100, 14908823, 53.82],
 ['20210608', 82300, 82600, 81800, 81900, 12781226, 53.8],
 ['20210607', 82700, 82800, 81600, 81900, 16496197, 53.82],
 ['20210604', 82700, 82700, 81500, 82200, 18112259, 53.84],
 ['20210603', 81300, 83000, 81100, 82800, 29546007, 53.82],
 ['20210602', 80400, 81400, 80300, 80800, 16414644, 53.73],
 ['20210601', 80500, 81300, 80100, 80600, 14058401, 53.69],
 ['20210531', 80300, 80600, 79600, 80500, 13321324, 53.69],
 ['20210528', 79800, 80400, 79400, 80100, 12360199, 53.64],
 ['20210527', 80000, 80000, 79100, 79600, 23198510, 53.64],
 ['20210526', 80400, 80500, 79700, 79800, 11984359, 53.68],
 ['20210525', 80000, 80400, 79800, 79900, 13628942, 53.68],
 ['20210524', 80100, 80400, 79500, 79700, 13398666, 53.71],
 ['20210521', 80100, 81500, 79800, 80100, 20961714, 53.74],
 ['20210520', 79400, 79700, 79100, 79500, 16541828, 53.72],
 ['20210518', 79600, 80000, 79100, 79600, 17494407, 53.75],
 ['20210517', 80800, 80900, 79200, 79600, 17740855, 53.84],
 ['20210514', 79000, 80300, 78900, 80100, 16450920, 53.9],
 ['20210513', 78900, 79600, 78400, 78500, 31490096, 53.89],
 ['20210512', 80800, 81200, 79800, 80000, 35812268, 54.07],
 ['20210511', 82500, 82600, 81100, 81200, 28996680, 54.31],
 ['20210510', 82300, 83500, 81800, 83200, 19385027, 54.47],
 ['20210507', 81800, 82100, 81500, 81900, 14154882, 54.46],
 ['20210506', 81700, 82300, 81700, 82300, 17047511, 54.49],
 ['20210504', 81900, 82600, 81800, 82600, 12532550, 54.55],
 ['20210503', 81000, 82400, 81000, 81700, 15710336, 54.55],
 ['20210430', 81900, 82100, 81500, 81500, 18673197, 54.59],
 ['20210429', 82400, 82500, 81500, 81700, 20000973, 54.61],
 ['20210428', 83200, 83200, 82100, 82100, 15596759, 54.69],
 ['20210427', 83200, 83300, 82500, 82900, 12941533, 54.7],
 ['20210426', 82900, 83500, 82600, 83500, 15489938, 54.7],
 ['20210423', 81900, 82900, 81600, 82800, 17805080, 54.67],
 ['20210422', 82900, 83000, 82400, 82400, 13934746, 54.68],
 ['20210421', 83300, 83500, 82500, 82600, 21636079, 54.72],
 ['20210420', 83300, 84000, 83100, 83900, 15521965, 54.78],
 ['20210419', 83800, 84000, 83300, 83300, 15287311, 54.76],
 ['20210416', 84700, 84700, 83600, 83900, 15429522, 54.81],
 ['20210415', 83700, 84500, 83400, 84100, 16377412, 54.81],
 ['20210414', 84000, 84300, 83400, 84000, 13794652, 54.79],
 ['20210413', 83000, 84500, 82800, 84000, 15238206, 54.8],
 ['20210412', 84100, 84100, 83100, 83200, 12915282, 54.78],
 ['20210409', 84700, 84900, 83400, 83600, 18193707, 54.79],
 ['20210408', 85700, 85700, 84100, 84700, 19244259, 54.83],
 ['20210407', 86100, 86200, 85400, 85600, 17885538, 54.82],
 ['20210406', 86200, 86200, 85100, 86000, 19042023, 54.8],
 ['20210405', 85800, 86000, 84800, 85400, 16255990, 54.73],
 ['20210402', 84000, 85200, 83900, 84800, 22997538, 54.73],
 ['20210401', 82500, 83000, 82000, 82900, 18676461, 54.6],
 ['20210331', 82400, 82700, 81400, 81400, 17240518, 54.54],
 ['20210330', 81600, 82300, 81300, 82200, 13121698, 54.57],
 ['20210329', 81700, 81700, 81000, 81600, 14952134, 54.56],
 ['20210326', 81400, 81600, 81000, 81500, 12845778, 54.58],
 ['20210325', 81000, 82100, 80800, 81200, 14758826, 54.69],
 ['20210324', 81000, 81600, 80700, 81000, 17926638, 54.68],
 ['20210323', 82600, 82900, 81800, 81800, 13299907, 54.71],
 ['20210322', 82000, 82300, 81700, 82000, 12670506, 54.73],
 ['20210319', 82100, 82500, 81800, 81900, 15869700, 54.74],
 ['20210318', 82800, 83800, 82600, 82900, 18585244, 54.76],
 ['20210317', 82800, 82900, 82000, 82300, 11625146, 54.7],
 ['20210316', 82200, 83000, 82100, 82800, 12293537, 54.68],
 ['20210315', 82800, 82900, 81800, 81800, 13735798, 54.66],
 ['20210312', 83100, 83500, 82400, 82800, 13530573, 54.71],
 ['20210311', 81000, 82500, 81000, 82000, 23818297, 54.67],
 ['20210310', 82400, 82500, 80700, 80900, 20038422, 54.57],
 ['20210309', 81400, 81900, 80600, 81400, 25420764, 54.6],
 ['20210308', 82900, 83000, 81600, 82000, 17641256, 54.68],
 ['20210305', 81100, 82600, 81100, 82100, 20508971, 54.7],
 ['20210304', 82600, 83200, 82200, 82400, 24348331, 54.72],
 ['20210303', 83500, 84000, 82800, 84000, 19882132, 54.77],
 ['20210302', 85100, 85300, 83000, 83600, 33498180, 54.81],
 ['20210226', 82800, 83400, 82000, 82500, 38520800, 54.74],
 ['20210225', 84000, 85400, 83000, 85300, 34155986, 54.92],
 ['20210224', 81800, 83600, 81300, 82000, 26807651, 54.78],
 ['20210223', 81200, 82900, 81100, 82000, 20587314, 54.76],
 ['20210222', 83800, 84200, 82200, 82200, 25419886, 54.79],
 ['20210219', 82300, 82800, 81000, 82600, 25880879, 54.77],
 ['20210218', 83200, 83600, 82100, 82100, 21327683, 54.84],
 ['20210217', 83900, 84200, 83000, 83200, 18307735, 54.88],
 ['20210216', 84500, 86000, 84200, 84900, 20483100, 54.91],
 ['20210215', 83800, 84500, 83300, 84200, 23529706, 54.88],
 ['날짜', '시가', '고가', '저가', '종가', '거래량', '외국인소진율']]

In [83]:
a = 100

In [84]:
a == 100

True

In [88]:
int(input("값을 입력하세요")) + 100

값을 입력하세요 100

200

In [91]:
input_a = int(input("값을 입력하세요"))
if input_a == 100:
    print("입력값이 100이네요")
else:
    print("입력값이 100이 아니네요")

값을 입력하세요 105

입력값이 100이 아니네요

In [93]:
input_a = int(input("값을 입력하세요"))
if input_a <= 100:
    print("입력값이 100보다 작다")
elif input_a <= 200:
    print("입력값이 100보다 크고 200보다 작거나 같다")
else:
    print("200보다 큰 값 입력했네")

값을 입력하세요 201

200보다 큰 값 입력했네

- 사용자에게 값을 입력 받고,
- 입력값이 5보다 작으면 출력을 "걸어가세요"
- 입력값이 5~10까지 범위면 "버스"
- 입력값이 10을 초과하면 "택시"

In [96]:
input_a = int(input("값을 입력하세요"))
if input_a < 5:
    print("걸어가세요")
elif input_a <= 10:
    print("버스")
else:
    print("택시")

값을 입력하세요 11

택시

In [105]:
text3 = "김미영팀장입니다. {}님께서는 최저이율로 최고 {}만원까지 {}분이내 통장입금가능합니다."

In [107]:
print(text3.format("아무개", 5000, 10))

김미영팀장입니다. 아무개님께서는 최저이율로 최고 5000만원까지 10분이내 통장입금가능합니다.

In [108]:
["정민철" , "김민규", "권혜성"]

['정민철', '김민규', '권혜성']

In [111]:
kbo = [	'권광민',	'권민규',	'김기중',	'김도빈',	'김민우',	'김범수',	'김범준',	'김서현',	'김승일',	'김예준',	'김인환',	'김종수',	'김태연',	'노시환',	'류현진',	'문동주',	'문승진',	'문현빈',		]

In [115]:
type(kbo)

list

In [113]:
kbo[-4:]

['류현진', '문동주', '문승진', '문현빈']

In [121]:
for name in kbo:
    if name == "류현진" or name == '김인환' or name == '김기중':
        print(text3.format(name, 1000000, 1))
    else:
        print(text3.format(name, 5000, 30))

김미영팀장입니다. 권광민님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 권민규님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김기중님께서는 최저이율로 최고 1000000만원까지 1분이내 통장입금가능합니다.
김미영팀장입니다. 김도빈님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김민우님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김범수님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김범준님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김서현님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김승일님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김예준님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김인환님께서는 최저이율로 최고 1000000만원까지 1분이내 통장입금가능합니다.
김미영팀장입니다. 김종수님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김태연님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 노시환님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 류현진님께서는 최저이율로 최고 1000000만원까지 1분이내 통장입금가능합니다.
김미영팀장입니다. 문동주님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 문승진님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 문현빈님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.

In [126]:
'엔코아' in kbo

False

In [127]:
for name in kbo:
    if name in [ "류현진" , '김인환' , '김기중']:
        print(text3.format(name, 1000000, 1))
    else:
        print(text3.format(name, 5000, 30))

김미영팀장입니다. 권광민님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 권민규님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김기중님께서는 최저이율로 최고 1000000만원까지 1분이내 통장입금가능합니다.
김미영팀장입니다. 김도빈님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김민우님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김범수님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김범준님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김서현님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김승일님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김예준님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김인환님께서는 최저이율로 최고 1000000만원까지 1분이내 통장입금가능합니다.
김미영팀장입니다. 김종수님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 김태연님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 노시환님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 류현진님께서는 최저이율로 최고 1000000만원까지 1분이내 통장입금가능합니다.
김미영팀장입니다. 문동주님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 문승진님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.
김미영팀장입니다. 문현빈님께서는 최저이율로 최고 5000만원까지 30분이내 통장입금가능합니다.

In [129]:
for x in "abcdef":
    print(x)

a
b
c
d
e
f

In [136]:
for x in range(2, 20):
    if x % 2 == 0 or x % 3 == 0:
        print(x)

2
3
4
6
8
9
10
12
14
15
16
18

In [139]:
for x in range(2,10):
    if x % 2 == 0:
        for y in range(1,10):
            print("{} x {} = {}".format(x, y, x*y))

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72

In [140]:
for x in range(2,10):
    if x % 2 == 0:
        for y in range(1,10):
            print(f"{x} x {y} = { x*y}")

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72

In [142]:
tmp = []
for x in range(10):
    tmp.append(x)

In [143]:
tmp

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# list comprehension(리스트 축약형)

In [144]:
tmp2 = [x for x in range(10)]

In [145]:
tmp2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [146]:
tmp = []
for x in range(10):
    if x % 2 == 0:
        tmp.append(x)

In [148]:
tmp2 = [x for x in range(10) if x % 2 == 0]

In [149]:
tmp2

[0, 2, 4, 6, 8]

In [150]:
gugudan = []
for x in range(2,10):
    for y in range(1,10):
        gugudan.append("{} x {} = {}".format(x, y, x*y))

In [154]:
[f"{x} x {y} = {x*y}" for x in range(2,10) for y in range(1,10) if x % 2 ==0]

['2 x 1 = 2',
 '2 x 2 = 4',
 '2 x 3 = 6',
 '2 x 4 = 8',
 '2 x 5 = 10',
 '2 x 6 = 12',
 '2 x 7 = 14',
 '2 x 8 = 16',
 '2 x 9 = 18',
 '4 x 1 = 4',
 '4 x 2 = 8',
 '4 x 3 = 12',
 '4 x 4 = 16',
 '4 x 5 = 20',
 '4 x 6 = 24',
 '4 x 7 = 28',
 '4 x 8 = 32',
 '4 x 9 = 36',
 '6 x 1 = 6',
 '6 x 2 = 12',
 '6 x 3 = 18',
 '6 x 4 = 24',
 '6 x 5 = 30',
 '6 x 6 = 36',
 '6 x 7 = 42',
 '6 x 8 = 48',
 '6 x 9 = 54',
 '8 x 1 = 8',
 '8 x 2 = 16',
 '8 x 3 = 24',
 '8 x 4 = 32',
 '8 x 5 = 40',
 '8 x 6 = 48',
 '8 x 7 = 56',
 '8 x 8 = 64',
 '8 x 9 = 72']

In [ ]:
서력 기원 연수가 4로 나누어 떨어지는 해는 윤년으로 한다. (1972년, 1976년, 1980년, 1984년, 1988년, 1992년, 1996년, 2000년, 2004년, 2008년, 2012년, 2016년, 2020년, 2024년, 2028년, 2032년, 2036년, 2040년, 2044년, 2048년, 2052년 ...)
서력 기원 연수가 100으로 나누어 떨어지는 해는 평년으로 한다. (1700년, 1800년, 1900년, 2100년, 2200년, 2300년...)
서력 기원 연수가 400으로 나누어 떨어지는 해는 윤년으로 둔다. (1600년, 2000년, 2400년...)

1900~2100 사이의 윤년 출력

In [162]:
leak_year = [year for year in range(1900,2101) if (year % 4 == 0) and (year % 100 != 0) or  (year % 400  == 0 ) ]

In [161]:
for year in range(1900,2101):
    if (year % 4 == 0) and (year % 100 != 0) or  (year % 400  == 0 )  :
        print(year)

[1904,
 1908,
 1912,
 1916,
 1920,
 1924,
 1928,
 1932,
 1936,
 1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020,
 2024,
 2028,
 2032,
 2036,
 2040,
 2044,
 2048,
 2052,
 2056,
 2060,
 2064,
 2068,
 2072,
 2076,
 2080,
 2084,
 2088,
 2092,
 2096]

In [164]:
{"a" : 10 , 100: 200}

{'a': 10, 100: 200}

In [170]:
import requests 
url = "https://www.starbucks.co.kr/store/getStore.do?r=86N465IIB2"
payload = {"in_biz_cds": "0",
"in_scodes": "0",
"ins_lat": "37.4745",
"ins_lng": "126.8918",
"search_text": "",
"p_sido_cd": "01",
"p_gugun_cd": "",
"in_distance": "0",
"in_biz_cd": "",
"isError": "true",
"searchType": "C",
"set_date": "",
"all_store": "0",
"T03": "0",
"T01": "0",
"T27": "0",
"T12": "0",
"T09": "0",
"T30": "0",
"T05": "0",
"T22": "0",
"T21": "0",
"T36": "0",
"T43": "0",
"Z9999": "0",
"T64": "0",
"T66": "0",
"P02": "0",
"P10": "0",
"P50": "0",
"P20": "0",
"P60": "0",
"P30": "0",
"P70": "0",
"P40": "0",
"P80": "0",
"whcroad_yn": "0",
"P90": "0",
"P01": "0",
"new_bool": "0",
"iend": "1000",
"rndCod": "XW4W0LA4X8",}
r = requests.post(url, data=payload)
star = r.json()

In [172]:
type(star)

dict

In [175]:
star_list = star['list']

In [176]:
len(star_list)

641

In [179]:
star_list[-1]['s_name']

'중화역'

In [180]:
type(star_list)

list

In [181]:
for store in star_list:
    print(store['s_name'])

역삼아레나빌딩
논현역사거리
신사역성일빌딩
국기원사거리
대치재경빌딩
봉은사역
압구정윤성빌딩
코엑스별마당
삼성역섬유센터R
압구정R
수서역R
양재강남빌딩R
선릉동신빌딩R
봉은사로선정릉
강남오거리
스타필드코엑스몰R
강남구청정문
도곡공원
강남R
대치은마사거리
청담영동대로
압구정
신사가로수
청담스타R
강남우성
학동사거리
대치사거리
포스코사거리
을지병원사거리
신사역
도곡역
서울세관사거리
청담사거리
한티역
역삼초교사거리
코엑스몰
가로수길
역삼대로
역삼포스코
강남대로
청담
삼성도심공항
삼성교
학동역
대치
신세계푸드마켓도곡
삼성
선릉세화빌딩
압구정역
압구정로
구역삼사거리
큰길타워
강남구청역
대치역
포이
아크플레이스
학여울역
선정릉역
삼성현대힐
GS타워
압구정미소
선릉역
코엑스사거리
역삼럭키
신압구정
아크로힐스논현
강남비젼타워
압구정로데오역
르네상스사거리
포스코
선릉로
논현힐탑
도산가로수길
매봉역
대치한티
개포동
수서역사거리
코엑스아셈타워
센터필드R
도산사거리
강남세곡
대치삼성
언주역
강남역신분당역사
삼성역
테헤란로아남타워
강남논현
삼성동
리저브도산
압구정역사3번출구
청담역
압구정현대아파트
강남청담빌딩
역삼이마트
케이스퀘어강남
강남세곡DT
미아뉴타운
강북구청사거리
미아사거리역
수유역
미아역
수유역5번출구
파라스파라서울
발산역사거리
마곡역
우장산역
마곡사이언스타워R
방화DT
마곡나루역
마곡GMG
가양역
화곡DT
양천향교역
화곡동
등촌
염창역
발산역
까치산역
염창대로
발산역5번출구
화곡역8번출구
강서우장산
등촌대로
마곡보타닉게이트
가양역사거리
원그로브
내발산
마곡웰튼
김포공항DT
강서NC
김포공항국제선
마곡케이스퀘어
마곡나루공원
송정역
강서구청사거리
낙성대역
관악서울대입구R
신림DT
서울대역
낙성대DT
사당
보라매대교
신림
신림타임스트림
서울대입구역
서울대입구역8번출구
봉천역
봉천현대시장
건국대
어린이대공원역
아차산역
올림픽대교북단
구의DT
자양사거리
군자역
광나루
건대스타시티
건대입구
구의역
광장
건국클래식
건대후문
중곡역
자양이마트
자양역
화양삼거리
군자사거리
금천구청역
가산에스케이
독산사거리
금천시흥
가산디지털단지역
금천독산
가산디지털
마리오아울렛
가산브이타워
독산역
가산퍼블릭
가산현대아울렛
가산케이에스
가산어반워크
월계역
월계트레이더스
상계초교사거리
공릉DT
노원마들역
공릉역
은행사거리
노원KT
광운대
중계역
노원역
월계이마트
태릉입구역DT
노원상계
노원구청
창동이마트
쌍문역
도봉구청
쌍문도봉로
도봉로DT
방학역
창동역
노량진동
남성역
상도역
보라매공원R
이수자이
노량진역
신대방삼거리역
중앙대
숭실대입구역
숭실대
사당역
상도대로
이수역13번출구
서강대프라자
상암YTN
마포용강동
홍대입구역사거리R
마포경찰서후문
공덕
합정폴리스R
홍대공항철도역
마포염리
서강광흥창역
합정
서강대흥역
서교동사거리
상암사보이시티
신촌오거리
상암디지털큐브
상수역
공덕오거리
서강대
상암MBC
홍대역
동교
애오개역
상암DMC
마포일진빌딩
마포아크로
홍대삼거리
망원역
마포이마트
합정메세나몰
아현역대로
디지털미디어시티역
홍대역8번출구
합정푸르지오
홍대동교
망원한강공원
마포구청역
가재울뉴타운
남가좌사거리
신촌역
아현역
홍제역
연세백양로
연희DT
경기대
신촌
이대
연세종합관
이대ECC
연대
충정로역
연대동문
신촌명물거리
충정타워
이대역
신촌로
북가좌DT
현대신촌
방배로
강남교보타워R
방배다이치빌딩
센트럴F1
서초역이화빌딩
서초구청
서초우성사거리
이수역사거리
강남대로신사
서울고속터미널
방배
방배카페거리
서초법원
청계산입구역
사당로데오
파미에파크R
양재역
논현역
이수역
내방역
서초파라곤
서울아트센터
서초중앙로
센트럴시티
방배역
반포역
남부터미널
뉴코아강남
강남서초초교
교대
하이브랜드
영동2교
남부터미널역5번출구
서래마을입구
몬테소리
서초역
교대법원
강남GT타워
서초동
서울교대
강남에비뉴
반포자이
서초태우빌딩
교대역3번출구
반포원베일리
양재역신분당역사
강남역우송빌딩
남부순환로방배DT
서이초교사거리
서울웨이브아트센터
강남삼성타운
신논현역
길음역
미아이마트
종암DT
미아
성신여대정문
종암
삼선교
월곡역
고대
현대미아
성신여대
안암역
한성대입구역
길음뉴타운
고대안암병원
장위뉴타운
성신여대입구역
송파나루역DT
송파헬리오시티
잠실시그마타워
문정법원로R
송파개롱역
문정하비오
문정역
잠실대교남단R
송파위례
송파방이DT
올림픽평화의문
송파아이파크
송파사거리
석촌서호
문정로데오
올림픽훼미리
올림픽공원남문
방이역
석촌호수
잠실푸르지오월드
잠실새내역
잠실역
갤러리아팰리스
아시아선수촌
올림픽아파트
가락본동
석촌역
가락시장역
가든파이브
문정역2번출구
잠실본동
송파NC
송파거여역
몽촌토성역
송파KT
문정법조타운 한양타워
송파마천사거리DT
목동파리공원
등촌역
목동행복한
신정DT
목동역
목동오목로
목동8단지
오목교역
신월IC DT
목동7단지
목동5단지
목동
현대목동
목동SBS
목동트라팰리스
목동10단지
신월동DT
타임스퀘어R
샛강역
영등포역
당산대로
여의도IFC몰(L1)R
여의도KBS R
여의도화재보험
국회대로
영등포KT
여의도공원R
국회의사당역
여의도역R
선유동이레빌딩
동여의도
여의도ABL타워
영등포신길
문래역
당산
여의도한양증권
여의도일신
하이테크시티
여의도
롯데캐슬여의도
문래동
여의도호성
타임스퀘어B2
영등포본동
타임스퀘어2F
여의도의사당
여의도IFC(1F)
여의도교직원공제회
선유도역 1번출구
영등포시장역
영등포구청역
서울양평역
영등포시장교차로
더현대서울(B2)R
여의도브라이튼
여의도TP타워
당산역사거리
신풍역
불광역
구파발사거리
연신내역사거리
연신내
구파발역
은평구청입구
은평이마트
구산역
불광역8번출구
응암역2번출구
수색
새절역
더북한산
녹번역
진관DT
연신내역5번출구
연합뉴스
혜화역
경희궁로
강북삼성병원
종로평창동
광화문우체국
종로R
독립문역
정부서울청사R
종로구청
북촌로
종로수송
새문안로
안국
삼청동
광화문D타워
적선
인사
광화문
성대입구
스페이스본
주얼리시티
종각
동숭로아트
종로관철
경복궁역
이마빌딩
마로니에공원
종로3가
대학로
경복궁사거리
종로관수
광화문교보문고
정동
종로플레이스
강북삼성병원1층
동숭길입구
서울대치과병원
서대문적십자
서대문역
숭례문북창
을지로4가역
동대문두타
대한상공회의소R
국립중앙의료원
동국대
동대문공원
을지로국제빌딩
동대입구역
신당역사거리
연세세브란스
회현역
을지로경기빌딩
을지로2가
신세계본점6F
서울중앙우체국
한국프레스센터
명동중앙로
약수역
중구저동
명동길
서소문로
신당역
명동메트로
숭례문
순화동더샵
환구단
무교동
문화일보
태평로
퍼시픽타워
남산단암
황학캐슬
을지로삼화타워
소공로
을지로한국빌딩
시청
명동역
장충라운지R
충무로
이마트타워
동호로
무교로
청계크리스탈스퀘어
숭례문SG타워
세종대로
동대문디자인플라자
별다방
포포인츠명동
명동남산
명일역
강동구청DT
강동암사DT
굽은다리역
강동역
둔촌동
천호로데오
천호이마트
길동역
상일동
천호역
명일이마트
상일동역
천호사거리
강일역
올림픽공원북2문
암사역
이케아강동
강동강일
천호대로길동
구로디지털타워
오류동역
구로디지털로
구로에이스
구로하이엔드
구로호텔
구로고척
구로NC
구로오류DT
구로구청
고척아이파크
신도림힐스테이트
현대디큐브2F
현대디큐브B2
답십리역
경희대삼거리
외대정문
신설동역
회기역사거리
장한평역
경희대
청량리역롯데캐슬스카이
경희의료원
경동1960
사이버한국외대
청량리역사
답십리초교사거리
장안사거리
서울숲역
금호역
뚝섬역
황학사거리
성수역
상왕십리역
왕십리역
한양대
엔터식스
신금호역
뚝섬역교차로
왕십리역9번출구
성수
옥수
성수낙낙
효창공원앞역
서울역서부
이태원역
한강진역R
용산역써밋R
이촌
신용산역
용산파크타워
남영동
한남동R
서울타워
서울역동자동
순천향입구
동빙고
숙대입구역
용산아이파크몰6F
동부이촌동
숙명여대정문
용산해링턴스퀘어
경리단길
서울역사
용산리첸시아
용산전자랜드
용산이마트
용산아이파크몰1F
상봉
중랑역
중랑구청
사가정역
상봉역
묵동
망우동
양원역
중화역